openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths: {}
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
        - locations
        - path
        - extensions
        - code
        - kind
        - name
        - source
        - tracing
      properties:
        message:
          type: string
        locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        path:
          type: array
          items:
            type: string
        extensions:
          $ref: "#/components/schemas/ErrorExtensions"
        code:
          type: integer
        kind:
          type: string
        name:
          type: string
        source:
          type: string
        retry_after:
          type: integer
        tracing:
          $ref: "#/components/schemas/Tracing"

    Location:
      type: object
      required:
        - line
        - column
      properties:
        line:
          type: integer
        column:
          type: integer

    ErrorExtensions:
      type: object
      required:
        - name
        - source
        - code
        - kind
        - tracing
      properties:
        name:
          type: string
        source:
          type: string
        retry_after:
          type: integer
        code:
          type: integer
        kind:
          type: string
        tracing:
          $ref: "#/components/schemas/Tracing"

    Tracing:
      type: object
      required:
        - trace_id
      properties:
        trace_id:
          type: string
          pattern: "^[0-9a-f]{16}$"
