openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1
paths: {}
components:
  schemas:
    TypeName:
      type: string
      enum:
        [
          TimelineTweet,
          TimelineTimelineItem,
          TimelineUser,
          TimelineTimelineCursor,
          TweetWithVisibilityResults,
          TimelineTimelineModule,
          TweetTombstone,
          TimelinePrompt,
          TimelineMessagePrompt,
          TimelineCommunity,
          TweetUnavailable,
          Tweet,
          User,
          UserUnavailable,
          Community,
          CommunityDeleteActionUnavailable,
          CommunityJoinAction,
          CommunityLeaveActionUnavailable,
          CommunityTweetPinActionUnavailable,
          CommunityInvitesUnavailable,
          CommunityJoinRequestsUnavailable,
        ]
