openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{pathQueryId}/Following:
    get:
      operationId: getFollowing
      description: get user list of following
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FollowResponse"
      tags:
        - "user-list"

  /graphql/{pathQueryId}/Followers:
    get:
      operationId: getFollowers
      description: get user list of followers
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FollowResponse"
      tags:
        - "user-list"

components:
  schemas:
    FollowResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/FollowResponseData"

    FollowResponseData:
      required:
        - "user"
      properties:
        user:
          $ref: "#/components/schemas/FollowResponseUser"

    FollowResponseUser:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/FollowResponseResult"

    FollowResponseResult:
      required:
        - "__typename"
        - "timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # User
        timeline:
          $ref: "#/components/schemas/FollowTimeline"

    FollowTimeline:
      required:
        - "timeline"
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
