openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{pathQueryId}/HomeTimeline:
    get:
      operationId: getHomeTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/TimelineResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/HomeLatestTimeline:
    get:
      operationId: getHomeLatestTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/TimelineResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/ListLatestTweetsTimeline:
    get:
      operationId: getListLatestTweetsTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/ListLatestTweetsTimelineResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/SearchTimeline:
    get:
      operationId: getSearchTimeline
      description: search tweet list. product:[Top, Latest, People, Photos, Videos]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/SearchTimelineResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "tweet"

components:
  schemas:
    TimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/HomeTimelineResponseData"

    HomeTimelineResponseData:
      required:
        - "home"
      properties:
        home:
          $ref: "#/components/schemas/HomeTimelineHome"

    HomeTimelineHome:
      required:
        - "home_timeline_urt"
      properties:
        home_timeline_urt:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    ListLatestTweetsTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/ListTweetsTimelineData"

    ListTweetsTimelineData:
      required:
        - "list"
      properties:
        list:
          $ref: "#/components/schemas/ListTweetsTimelineList"

    ListTweetsTimelineList:
      required:
        - "tweets_timeline"
      properties:
        tweets_timeline:
          $ref: "#/components/schemas/ListTweetsTimeline"

    ListTweetsTimeline:
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    SearchTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/SearchTimelineData"

    SearchTimelineData:
      required:
        - "search_by_raw_query"
      properties:
        search_by_raw_query:
          $ref: "#/components/schemas/SearchByRawQuery"

    SearchByRawQuery:
      required:
        - "search_timeline"
      properties:
        search_timeline:
          $ref: "#/components/schemas/SearchTimeline"

    SearchTimeline:
      required:
        - "timeline"
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
