openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{pathQueryId}/TweetDetail:
    get:
      operationId: getTweetDetail
      description: get TweetDetail
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TweetDetailResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/Favoriters:
    get:
      operationId: getFavoriters
      description: get tweet favoriters
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TweetFavoritersResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "user-list"

  /graphql/{pathQueryId}/Retweeters:
    get:
      operationId: getRetweeters
      description: get tweet retweeters
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/TweetRetweetersResponse"
                  - $ref: "./../schemas/error.yaml#/components/schemas/Errors"
      tags:
        - "user-list"

components:
  schemas:
    TweetDetailResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/TweetDetailResponseData"

    TweetDetailResponseData:
      required:
        - "threaded_conversation_with_injections_v2"
      properties:
        threaded_conversation_with_injections_v2:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    TweetFavoritersResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/TweetFavoritersResponseData"

    TweetFavoritersResponseData:
      required:
        - "favoriters_timeline"
      properties:
        favoriters_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineV2"

    TweetRetweetersResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/TweetRetweetersResponseData"

    TweetRetweetersResponseData:
      required:
        - "retweeters_timeline"
      properties:
        retweeters_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineV2"
