openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{queryId}/TweetDetail:
    get:
      operationId: getTweetDetail
      description: get TweetDetail
      parameters:
        - $ref: "../resources/parameters.yaml#/components/parameters/queryId"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TweetDetailResponse"
      tags:
        - "tweet"

components:
  schemas:
    TweetDetailResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/TweetDetailResponseData"

    TweetDetailResponseData:
      required:
        - "threaded_conversation_with_injections_v2"
      properties:
        threaded_conversation_with_injections_v2:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
