openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /1.1/friendships/create.json:
    post:
      operationId: postCreateFriendships
      description: post create friendships
      responses:
        "200":
          description: Successful operation
      tags:
        - "v1.1"
